### ISSUE TITLE
Use pip for py deps, require installing Python & system deps manually

### ISSUE THREAD

**Issue by jaydenkieran** [Cheeselab/DecoraterBot#10]
Seriously, this is bad. Why include the binaries for Python and the dependencies rather than make users install them properly?

**Comment by AraHaan** [comment]
Well some users like portability and I do as well Also DecoraterBotCore is not on PyPi and updates to much to be on it yet because of Discord API changes and some bugs on it as well.
I do also know some optimizations and not only that but some people dont want to install python on a system they do not have privlages to install anything to. Hence portability. Plus it can take a long times sometimes installing a lot of stuff not to mention pip generates bytecode I dont use. and plus I perfer ``sys.dont_write_bytecode`` set to ``True``. I am working on addign docstrings to things as well. However they might have issues explaining stuff as that is a pretty normal thing with me.
Also since the ``Core`` is not installable manually (without issues findign the dependencies with the sys.path appends it relies on all because it gets ImportErrors from internal core modules for some unknown reason. if I was to fix those then yeah it would be fine. But keep in mind I use embed version of python so I can easily build 3.6 on the release day myself and not have to install it due to limited disc space. So as a benefit I can save more than 50 MB or so just by using a ``minified`` embed copy that has the deps to run the bot in python35.zip other than the addons that are not normally shipped with the interpreter.

So, yeah there is portability and disc space needs.

**Comment by AraHaan** [comment]
I did at 1 time have a branch for optionally installing the deps but since issues popped up it made it impossible plus working on a global ``portable`` way is so beneficial and time saving.

**Comment by AraHaan** [comment]
Ok, for the linux ones, I currently recommend using and / or installing 3.5.2 for your 32 or 64 bit linux.

After that, install the following packages:

> aiohttp (latest perfered)

> pynacl (latest perfered)

> cffi (if not installed with pynacl)

And the rest of the dependencies should be located in ``dependencies.linux.zip``. I have left a person in charge of that zip file as i do not use linux myself. So they should pull request my repo every time I change the window's ones with a updated linux zip file.

**Comment by AraHaan** [comment]
I will still ship the binaries to linux I just need jakesden to compile the python 3.5.2 standard lib to a zip file that can be used for both the 32 and 64 bit linux ones to test again.

**Comment by AraHaan** [comment]
Well, This must be done for the linux Platform please read the readme at the top of this repo. (I changed it to list the packages that should need to be installed to use the bot. Also 1 linux ``sh`` file is needed so I removed the other one.

**Comment by GetRektByMe** [comment]
Can I ask why on earth you add so many labels, it kinda seems like you're trying to make your terrible bot useful through making it look like you're doing more work than you are behind the scenes

**Comment by jaydenkieran** [comment]
Hey @AraHaan, @jakesden is currently sat in the python_discord-py channel in the Discord API server asking for help because he doesn't know how to make binaries work for Linux. Maybe you should get someone more intelligent.

p.s he also tried to create `discord.Message()` manually so he has probably fucked your code up somewhere

Love,
Your friends @ the discord_discord-py channel

**Comment by GetRektByMe** [comment]
On top of that, @AraHaan can you never teach Python again - I'd rather be taught C++ by a toddler; for one it seems pretty obvious you spoonfeed anyone you teach - and you can't even spoonfeed decent code ffs, please man, save the children

**Comment by jaydenkieran** [comment]
Hey @AraHaan, @jakesden is currently sat in the python_discord-py channel in the Discord API server asking for help because he doesn't know how to make binaries work for Linux. Maybe you should get someone more intelligent.

p.s he also tried to create `discord.Message()` manually so he has probably fucked your code up somewhere

Love,
Your friends @ the discord_discord-py channel

**Comment by jaydenkieran** [comment]
Also he keeps deleting my comments, so teach him how to be mature pls

**Comment by AraHaan** [comment]
@GetRektByMe actually I plan to make all event that discord.py supports get used (mostly for logs and some other things for debugging reasons in case stuff breaks or whatever.

However I get muisy with a lot of stuff like school, and was definately buisy with helping my mom move by packing and litterally lifting heavy shit which proves to be a pain in the ass.
