### ISSUE TITLE
Clean up your functions

### ISSUE THREAD

**Issue by jaydenkieran** [Cheeselab/DecoraterBot#13]
For example, in `BotLogs.py`, these can be made into literally one function that can be given a different argument depending on which one you want to 'set up'.

```
    def set_up_discord_logger_code(self):
        logger = logging.getLogger('discord')
        logger.setLevel(logging.DEBUG)
        handler = logging.FileHandler(filename='{0}{1}resources{1}Logs{1}discordpy.log'.format(sys.path[0], sepa), encoding='utf-8', mode='w')
        handler.setFormatter(logging.Formatter('%(asctime)s:%(levelname)s:%(name)s: %(message)s'))
        logger.addHandler(handler)

    def set_up_asyncio_logger_code(self):
        asynciologger = logging.getLogger('asyncio')
        asynciologger.setLevel(logging.DEBUG)
        handler = logging.FileHandler(filename='{0}{1}resources{1}Logs{1}asyncio.log'.format(sys.path[0], sepa), encoding='utf-8', mode='w')
        handler.setFormatter(logging.Formatter('%(asctime)s:%(levelname)s:%(name)s: %(message)s'))
        asynciologger.addHandler(handler)
```

**Comment by AraHaan** [comment]
the issue with this is I want to make it able to set both up. However only the Discord.py one work for now. I am currently looking into why and I asked in the #python channel on Freenode (with no answers). I do have problems with some naminv of functions since I have recently found out that prefixing any function with ``_`` before anything else in the name makes it considered ``Protected`` in Python's point of view.

**Comment by AraHaan** [comment]
look in 913d2ecc6420270401e54db6f0a09bc37f85893a.
